# Generated by Django 4.2.1 on 2023-06-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inter',
            fields=[
                ('collage_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('school_name', models.ForeignKey(max_length=70, on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=80)),
                ('collage_name', models.ForeignKey(max_length=90, on_delete=django.db.models.deletion.CASCADE, to='app.inter')),
            ],
        ),
    ]
